export const ACTION_CONT = {
  RECEIVED_TODOS_LIST: "RECEIVED_TODOS_LIST",
  GET_TODOS_LIST: "GET_TODOS_LIST",
  RECEIVED_TODO: "RECEIVED_TODO",
  GET_TODO: "GET_TODO",
  ADD_TODO: "ADD_TODO",
  TOGGLE_TODO: "TOGGLE_TODO",
  DELETE_TODO: "DELETE_TODO",
  EDIT_TODO: "EDIT_TODO",
  SELECT_TODO: "SELECT_TODO",
};
